version: '3.3'

services:
  redis:
    container_name: redis
    image: redis:5.0
    environment:
      TZ: "Asia/Shanghai"
    restart: always

  nginx:
    container_name: local-nginx
    image: nginx:1.18.0
    ports:
      - "80:80"
    volumes:
      - .:/var/www/oa_project_end
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: local-php
    build:
      context: ..
      dockerfile: Dockerfile
    image: local-php
    volumes:
      - .:/var/www/oa_project_end
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - redis
    environment:
      TZ: "Asia/Shanghai"
      REDIS_HOST: "redis"

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./dbService/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./logData/mysql:/var/lib/mysql/:rw
      - ./logServer/mysql:/var/log/mysql:rw
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWARD: "1234321"
      TZ: "Asia/Shanghai"
    networks:
      - host

networks:
  host: